export const routes = {
  loginRoute: '/login',
  workshopRoute: '/workshop',
  customersRoute: '/customers',
  customersAddRoute: '/customers/add',
  usersRoute: '/users',
  usersAddRoute: '/users/add',
  housesRoute: '/houses',
  housesAddRoute: '/houses/add',
  houseRoute: '/houses/:id',
  houseAddDefectRoute: '/houses/:id/add-defect',
  houseEditDefectRoute: '/houses/:id/edit-defect/:defectId',
  houseAddDocumentRoute: '/houses/:id/add-documents',
  houseEditDocumentRoute: '/houses/:id/edit-documents/:documentId',
  customerRoute: '/customers/:id',
  eventLogsRoute: '/logs',
}
