export const routes = {
  loginRoute: '/login',
  workshopRoute: '/workshop',
  customersRoute: '/customers',
  customersAddRoute: '/customers/add',
  usersRoute: '/users',
  usersAddRoute: '/users/add',
  housesRoute: '/houses',
  housesAddRoute: '/houses/add',
  houseDetailsRoute: '/houses/:id/details',
  houseDefectsRoute: '/houses/:id/defects',
  houseAddDefectRoute: '/houses/:id/defects/add',
  houseEditDefectRoute: '/houses/:id/defects/:defectId/edit',
  houseDocumentsRoute: '/houses/:id/documents',
  houseAddDocumentRoute: '/houses/:id/documents/add',
  houseEditDocumentRoute: '/houses/:id/documents/:documentId/edit',
  houseChecklistRoute: '/houses/:id/checklist',
  customerRoute: '/customers/:id',
}