import React from 'react'
import { Button } from '@mui/material'
import { MdFileDownload } from 'react-icons/md'
import axios from 'axios'
const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

const ChecklistDownloadButton = ({ houseId }) => {
  const handleClick = async () => {
    try {
      const response = await axios({
        method: 'get',
        url: `${BACKEND_URL}/checklists/download/${houseId}`,
        responseType: 'blob',
      })
      downloadResponseBlob(response.data)
    } catch (error) {
      console.error(
        `Error downloading the checklist PDF for house ${houseId}:`,
        error
      )
    }
  }

  /*
  `downloadResponseBlob` was generated by ChatGPT-40 on July 30, 2024
  The prompt used was: "give me a short javascript function that will
  download a blob response from an axios get request as a pdf in a React
  frontend"
  The generated code was tested and accepted
   */
  const downloadResponseBlob = data => {
    const url = window.URL.createObjectURL(new Blob([data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', 'checklists.pdf') // Specify the file name
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link) // Clean up the DOM
  }

  return (
    <Button
      variant='contained'
      color='primary'
      onClick={handleClick}
      startIcon={<MdFileDownload />}
    >
      PDF
    </Button>
  )
}

export default ChecklistDownloadButton
