export const colors = {
  backgroundMain: '#12151F',
  appBarBackground: '#1E1F2A',
  appBarColor: '#1E1F2A',
  sideBarBackground: '#808080',
  sideBarColor: 'white',
  sideBarLinkActiveColor: 'grey',
  sideBarLinkInactiveColor: 'white',
  sideBarLinkActiveBackground: 'lightgrey',
  sideBarLinkInactiveBackground: 'grey',
  sideBarActiveIconColor: 'grey',
  sideBarInactiveIconColor: 'white',
  tableHeadCellBackground: '#171717bc',
  tableRowOddBackground: '#272626cb',
  dialogSecondaryButtonColor: 'grey',
  locationIconColor: '#FF4C4C',
  errorTextColor: 'red',
  arrowIconForLegendColor: 'grey',
}
